## * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
##   Makefile to test SZ library.

##   PLEASE SET THIS VARIABLE BEFORE COMPILING
ZCPATH          = /home/sdi/Install/z-checker-install
CUnit_HOME	= /home/sdi/Install/CUnit-2.1.3-install
##   COMPILERS
CC              = gcc

##   FLAGS
# Compiling using shared library
#ZCFLAG         = -I$(ZCPATH)/include -L$(ZCPATH)/lib -lsz
# Compiling using static library
ZCFLAG		= -I$(ZCPATH)/include $(ZCPATH)/lib/libzc.a -lm
CUnit_FLAG 	= -I$(CUnit_HOME)/include $(CUnit_HOME)/lib/libcunit.a

cunit_patch	= CUnit_Array.o

##   TARGETS
all: 		test_quicksort test_util test_conf test_DynamicIntArray test_DynamicByteArray test_DynamicFloatArray test_DynamicDoubleArray test_ByteToolkit

CUnit_Array.o:	CUnit_Array.c CUnit_Array.h
	$(CC) -Wall -c CUnit_Array.c -I$(CUnit_HOME)/include

test_conf:	test_conf.c
	${CC} -Wall -g -o test_conf test_conf.c $(CUnit_FLAG) $(ZCFLAG)

test_ByteToolkit:	$(cunit_patch) test_ByteToolkit.c
	${CC} -Wall -g -o test_ByteToolkit test_ByteToolkit.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_DynamicIntArray:	$(cunit_patch) test_DynamicIntArray.c
	${CC} -Wall -g -o test_DynamicIntArray test_DynamicIntArray.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_DynamicByteArray:	$(cunit_patch) test_DynamicByteArray.c
	${CC} -Wall -g -o test_DynamicByteArray test_DynamicByteArray.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_DynamicFloatArray:	$(cunit_patch) test_DynamicFloatArray.c
	${CC} -Wall -g -o test_DynamicFloatArray test_DynamicFloatArray.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_DynamicDoubleArray:	$(cunit_patch) test_DynamicDoubleArray.c
	${CC} -Wall -g -o test_DynamicDoubleArray test_DynamicDoubleArray.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_rw:	$(cunit_patch) test_rw.c
	${CC} -Wall -g -o test_rw test_rw.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_util:	$(cunit_patch) test_util.c
	${CC} -Wall -g -o test_util test_util.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

test_quicksort:	$(cunit_patch) test_quicksort.c
	${CC} -Wall -g -o test_quicksort test_quicksort.c $(cunit_patch) $(CUnit_FLAG) $(ZCFLAG)

clean:
	rm -rf *.o test_quicksort test_util test_conf test_ByteToolkit test_dataCompression test_DynamicIntArray test_DynamicByteArray test_DynamicFloatArray test_DynamicDoubleArray test_rw test_Huffman test_TypeManager
